# ==========================================================================
# AUTOMATICALLY GENERATED BY PHYTOCLASSSHINY SETUP
# ==========================================================================
Sys.setenv(PHYTOCLASSSHINY_SANDBOX_ACTIVE = 'TRUE')
.libPaths(base::file.path(base::getwd(), 'system', 'app_packages'))
base::cat('\n[✓] phytoclassShiny Sandbox Active\n')

if (interactive() && base::requireNamespace('rstudioapi', quietly = TRUE)) {
  if (rstudioapi::isAvailable()) {
    rstudioapi::navigateToFile('app.R')
    base::cat('\n[>] app.R loaded. Click \'Run App\' in the top right of the editor to start.\n\n')
  }
}
